# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import grabber.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('attachment', models.FileField(max_length=512, upload_to=grabber.models.generate_filename)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ('issue',),
                'verbose_name_plural': 'attachments',
                'verbose_name': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('key', models.CharField(max_length=10, unique=True)),
                ('link', models.URLField()),
                ('uid_dest', models.PositiveIntegerField(null=True, unique=True)),
                ('link_dest', models.URLField(blank=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name_plural': 'issues',
                'verbose_name': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('link', models.URLField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'versions',
                'verbose_name': 'version',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Issue'),
        ),
    ]
