"""
Django settings for jiragrabber project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ifox!*3o1le^n3j*3a(415le$&@he(&9%uoew1*os7jm1=c^ce'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',

    'grabber',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jiragrabber.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jiragrabber.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'jiragrabber',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

JIRA = {
    'SOURCE': {
        'HOST': 'https://source.jira.company.com',
        'AUTH': ('user', 'password'),

        'PROJECT_KEY': 'PRJ',
    },

    'DESTINATION': {
        'HOST': 'https://destination.jira.company.com',
        'AUTH': ('admin', 'password'),

        'PROJECT': {
            'KEY': 'PRJ',
            'ID': '10000',
        },

        'DEFAULT_USER_PASSWORD': 'changeme',
    }
}

SUBTASK_IDS = ["10201", "10503"]
STORY_ID = "10002"
EPIC_ID = "10001"

############
# MAPPINGS #
############

ISSUE_TYPES = {
    '10000': '10001',  # Epic (Epic)
    '10001': '10002',  # Story (Story)
    '1':     '10004',  # Bug (Bug)
    '10201': '10000',  # Sub-task (Sub-task)
    '10503': '10000',  # Исправление (Sub-task)
    '10304': '10002',  # TEX (Story)
    '10100': '10002',  # IT Help (Story)
}

# To Do - 11
# In Progress - 21
# Done - 31
STATUSES = {
    'Open': '11',
    'Разработка': '21',
    'Аналитика': '21',
    'Тестирование': '21',
    'На доработку': '21',
    'Переоткрыт': '21',
    'ФТ (завершено)': '21',
    'ФТ (требуется доработка)': '21',
    'Аналитика завершена': '21',
    'Контрольное тестирование': '21',
    'Документирование': '21',
    'Функциональное тестирование': '21',
    'Решена': '31',
    'Closed': '31',
}

LINK_TYPES = {
    'Blocks': 'Blocks',
    'Cloners': 'Cloners',
    'Duplicate': 'Duplicate',
    'Relates': 'Relates',
    'Исправление': 'Relates',
}
